name: custom_ner_api
channels:
  - defaults
dependencies:
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - openssl=1.1.1q
  - pip=22.2.2
  - python=3.8.13
  - sqlite=3.39.3
  - wheel=0.37.1
  - pip:
    - altair==4.2.0
    - amqp==5.1.1
    - anyio==3.6.1
    - asgiref==3.5.2
    - astroid==2.12.11
    - asttokens==2.0.8
    - attrs==22.1.0
    - auto-labeling-pipeline==0.1.21
    - autocorrect==2.6.1
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.11.1
    - billiard==3.6.4.0
    - black==22.10.0
    - blinker==1.5
    - boto3==1.24.89
    - botocore==1.27.89
    - brotli==1.0.9
    - catalogue==2.0.8
    - celery==5.2.7
    - cffi==1.15.1
    - cfgv==3.3.1
    - chardet==4.0.0
    - charset-normalizer==2.1.1
    - click-didyoumean==0.3.0
    - click-plugins==1.1.1
    - click-repl==0.2.0
    - colorama==0.4.5
    - commonmark==0.9.1
    - configargparse==1.5.3
    - coreapi==2.3.3
    - coreschema==0.0.4
    - coverage==6.5.0
    - cssselect==1.1.0
    - cymem==2.0.6
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - distlib==0.3.6
    - dj-database-url==0.5.0
    - dj-rest-auth==2.2.5
    - django==4.1.2
    - django-celery-results==2.2.0
    - django-cleanup==6.0.0
    - django-cors-headers==3.13.0
    - django-drf-filepond==0.4.1
    - django-filter==21.1
    - django-health-check==3.17.0
    - django-polymorphic==3.1.0
    - django-rest-polymorphic==0.1.10
    - django-storages==1.13.1
    - djangorestframework==3.14.0
    - djangorestframework-xml==2.0.0
    - doccano==1.8.0
    - drf-yasg==1.21.4
    - en-core-web-lg==3.4.0
    - entrypoints==0.4
    - environs==9.5.0
    - et-xmlfile==1.1.0
    - executing==1.1.1
    - fastapi==0.85.0
    - feedfinder2==0.0.4
    - feedparser==6.0.10
    - filelock==3.8.0
    - filetype==1.1.0
    - flask==2.2.2
    - flask-basicauth==0.2.0
    - flask-cors==3.0.10
    - flatbuffers==22.9.24
    - furl==2.1.3
    - gevent==22.8.0
    - geventhttpclient==2.0.2
    - greenlet==1.1.3.post0
    - gunicorn==20.1.0
    - h11==0.14.0
    - identify==2.5.6
    - idna==3.4
    - importlib-metadata==5.0.0
    - inflection==0.5.1
    - iniconfig==1.1.1
    - ipykernel==6.16.0
    - ipython==8.5.0
    - isort==5.10.1
    - itsdangerous==2.1.2
    - itypes==1.2.0
    - jedi==0.18.1
    - jieba3k==0.35.1
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.2.0
    - jsonschema==4.16.0
    - jupyter-client==7.4.2
    - jupyter-core==4.11.1
    - kombu==5.2.4
    - langcodes==3.3.0
    - langdetect==1.0.9
    - lazy-object-proxy==1.7.1
    - lml==0.1.0
    - locust==2.12.1
    - lxml==4.9.1
    - markupsafe==2.1.1
    - marshmallow==3.18.0
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - msgpack==1.0.4
    - mypy-extensions==0.4.3
    - nest-asyncio==1.5.6
    - newsapi-python==0.2.6
    - newspaper3k==0.2.8
    - nltk==3.7
    - nodeenv==1.7.0
    - numpy==1.23.4
    - openpyxl==3.0.10
    - orderedmultidict==1.0.1
    - packaging==21.3
    - pandas==1.5.0
    - parso==0.8.3
    - pathspec==0.10.1
    - pathtools==0.1.2
    - pathy==0.6.2
    - pickleshare==0.7.5
    - pillow==9.2.0
    - pkgutil-resolve-name==1.3.10
    - plac==1.1.3
    - platformdirs==2.5.2
    - pre-commit==2.20.0
    - prompt-toolkit==3.0.31
    - protobuf==3.20.3
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pycparser==2.21
    - pydantic==1.9.2
    - pydeck==0.8.0b4
    - pyexcel==0.7.0
    - pyexcel-io==0.6.6
    - pyexcel-xlsx==0.6.0
    - pygments==2.13.0
    - pylint==2.15.4
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - pytest==7.1.3
    - pytest-cov==4.0.0
    - python-dateutil==2.8.2
    - python-dotenv==0.21.0
    - pytz==2022.4
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==6.0
    - pyzmq==24.0.1
    - regex==2022.9.13
    - requests==2.28.1
    - requests-file==1.5.1
    - rich==12.6.0
    - roundrobin==0.0.4
    - rsa==4.9
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - s3transfer==0.6.0
    - scipy==1.9.2
    - semver==2.13.0
    - sentry-sdk==1.9.10
    - seqeval==1.2.2
    - setproctitle==1.3.2
    - setuptools==65.5.0
    - sgmllib3k==1.0.0
    - shortuuid==1.0.9
    - six==1.16.0
    - smart-open==5.2.1
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - spacy==3.4.1
    - spacy-alignments==0.8.5
    - spacy-legacy==3.0.10
    - spacy-loggers==1.0.3
    - spacy-lookups-data==1.0.3
    - spacy-transformers==1.1.8
    - sqlalchemy==1.4.41
    - sqlparse==0.4.3
    - srsly==2.4.4
    - stack-data==0.5.1
    - starlette==0.20.4
    - streamlit==1.13.0
    - termcolor==2.0.1
    - texttable==1.6.4
    - threadpoolctl==3.1.0
    - tinysegmenter==0.3
    - tldextract==3.4.0
    - tokenizers==0.12.1
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.11.5
    - toolz==0.12.0
    - torch==1.12.1
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.4.0
    - typer==0.4.2
    - typing-extensions==4.4.0
    - tzdata==2022.5
    - tzlocal==4.2
    - uritemplate==4.1.1
    - urllib3==1.26.12
    - uvicorn==0.18.3
    - validators==0.20.0
    - vine==5.0.0
    - virtualenv==20.16.5
    - waitress==2.1.2
    - wasabi==0.10.1
    - watchdog==2.1.9
    - wcwidth==0.2.5
    - werkzeug==2.2.2
    - whitenoise==6.2.0
    - wrapt==1.14.1
    - xxhash==3.0.0
    - zipp==3.9.0
    - zope-event==4.5.0
    - zope-interface==5.5.0
