# Python CircleCI 1.0 configuration file
version: 1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/code

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            conda env create -f environment.yml
            source activate custom_ner_api
        #or conda init bash
        # source ~/.bashrc
        #conda activate calculator   
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            source activate custom_ner_api
            pylint src
            pytest -vv